services:
  api:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - medbridge-phase2_default

networks:
  medbridge-phase2_default:
    external: true