"""add patient identity and verification fields

Revision ID: 1fd81a9e9deb
Revises: ac0767a44c87
Create Date: 2026-09-24 10:53:01.176674
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '1fd81a9e9deb'
down_revision: Union[str, Sequence[str], None] = 'ac0767a44c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('patients', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_name', sa.String(length=200), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True))
    op.add_column('patients', sa.Column('profile_photo_url', sa.String(length=500), nullable=True))
    op.add_column('patients', sa.Column('identity_verification_status', sa.String(length=30), nullable=True))
    op.add_column('patients', sa.Column('identity_verified_at', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('identity_verified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['identity_verified_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'identity_verified_by')
    op.drop_column('patients', 'identity_verified_at')
    op.drop_column('patients', 'identity_verification_status')
    op.drop_column('patients', 'profile_photo_url')
    op.drop_column('patients', 'emergency_contact_phone')
    op.drop_column('patients', 'emergency_contact_name')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'gender')
    # ### end Alembic commands ###
